In [ ]:
from google.colab import files

uploaded = files.upload()

Saving nykaa_campaign_data.csv to nykaa_campaign_data.csv

In [ ]:
import pandas as pd
x=pd.read_csv("nykaa_campaign_data.csv")
x.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  object
 1   Campaign_Type     55555 non-null  object
 2   Target_Audience   55555 non-null  object
 3   Duration          55555 non-null  int64
 4   Channel_Used      55555 non-null  object
 5   Impressions       55555 non-null  int64
 6   Clicks            55555 non-null  int64
 7   Leads             55555 non-null  int64
 8   Conversions       55555 non-null  int64
 9   Revenue           55555 non-null  int64
 10  Acquisition_Cost  55555 non-null  float64
 11  ROI               55555 non-null  float64
 12  Language          55555 non-null  object
 13  Engagement_Score  55555 non-null  float64
 14  Customer_Segment  55555 non-null  object
 15  Date              55555 non-null  object
dtypes: float64(3), int64(6), object(7)
memory usage: 6.8+ MB

In [ ]:
import numpy as np
x["Ci"] = ((x["Clicks"] / x["Impressions"])*100).replace(0, np.nan)
x["Lc"] = ((x["Leads"] / x["Clicks"])*100).replace(0, np.nan)
x["Cl"] = ((x["Conversions"] / x["Leads"])*100).replace(0, np.nan)
x["Cc"] = ((x["Conversions"] / x["Clicks"])*100).replace(0, np.nan)
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  object
 1   Campaign_Type     55555 non-null  object
 2   Target_Audience   55555 non-null  object
 3   Duration          55555 non-null  int64
 4   Channel_Used      55555 non-null  object
 5   Impressions       55555 non-null  int64
 6   Clicks            55555 non-null  int64
 7   Leads             55555 non-null  int64
 8   Conversions       55555 non-null  int64
 9   Revenue           55555 non-null  int64
 10  Acquisition_Cost  55555 non-null  float64
 11  ROI               55555 non-null  float64
 12  Language          55555 non-null  object
 13  Engagement_Score  55555 non-null  float64
 14  Customer_Segment  55555 non-null  object
 15  Date              55555 non-null  object
 16  Ci                55555 non-null  float64
 17  Lc                55555 non-null  float64
 18  Cl                55555 non-null  float64
 19  Cc                55555 non-null  float64
dtypes: float64(7), int64(6), object(7)
memory usage: 8.5+ MB

In [ ]:
x['ROI_check'] = (x['Revenue'] - x['Acquisition_Cost']) / x['Acquisition_Cost']
x[["ROI","ROI_check"]] #ROI SC
x.drop(columns="ROI",inplace=True)

In [ ]:
x["Ci"].describe()
x["Lc"].describe()
x["Cl"].describe()
x["Cc"].describe()

count    55555.000000
mean        21.971554
std          8.772756
min          5.961252
25%         15.263524
50%         20.474893
75%         27.784568
max         47.742624
Name: Cc, dtype: float64

In [ ]:
x["Date"]=pd.to_datetime(x["Date"])
x=x.sort_values(by="Date")
x['MonthYear'] = x['Date'].dt.strftime('%B %Y')
x.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,...,Language,Engagement_Score,Customer_Segment,Date,Ci,Lc,Cl,Cc,ROI_check,MonthYear
47076,NY-CMP-48076,Social Media,Premium Shoppers,25,"Instagram, Facebook",61091,7304,3199,1936,1500400,...,Bengali,20.36,Working Women,2024-07-01,11.955935,43.797919,60.518912,26.506024,13230.040564,July 2024
36387,NY-CMP-37387,Influencer,Working Women,30,"Facebook, WhatsApp",22936,3319,1675,633,250668,...,Bengali,24.53,Tier 2 City Customers,2024-07-01,14.470701,50.467008,37.791045,19.072010,684.409603,July 2024
26969,NY-CMP-27969,Email,Tier 2 City Customers,11,Facebook,68707,4985,1650,778,256740,...,Hindi,10.79,College Students,2024-07-01,7.255447,33.099298,47.151515,15.606820,1044.997148,July 2024
36294,NY-CMP-37294,SEO,Tier 2 City Customers,20,Instagram,58315,2780,1575,970,422920,...,Hindi,9.13,Premium Shoppers,2024-07-01,4.767213,56.654676,61.587302,34.892086,4321.125703,July 2024
32641,NY-CMP-33641,Paid Ads,Working Women,28,WhatsApp,20260,949,255,141,83472,...,Tamil,6.64,Youth,2024-07-01,4.684107,26.870390,55.294118,14.857745,41.615368,July 2024

In [ ]:
x["Campaign_ID"].duplicated().sum()
x["Campaign_Type"].value_counts()
x["Target_Audience"].value_counts()
x["Channel_Used"].value_counts() # info
x["Language"].value_counts()
x["Channel_Used"].value_counts()

Channel_Used
Instagram                       3178
YouTube                         3150
WhatsApp                        3096
Google                          3092
Email                           3060
                                ...
YouTube, WhatsApp, Facebook      129
Google, Facebook, Instagram      126
WhatsApp, YouTube, Email         125
YouTube, WhatsApp, Instagram     124
Email, YouTube, Facebook         107
Name: count, Length: 156, dtype: int64

In [ ]:
x["Duration"].describe() # dur 5:30 eq not outliers
import plotly.express as px
#px.box(x,x="Duration")
print("   ")

In [ ]:
x.loc[
    (x['Impressions'] >= x['Clicks']) &
    (x['Clicks'] >= x['Leads']) &
    (x['Leads'] >= x['Conversions']),
    'Impressions'
].count()
x.loc[(x["Acquisition_Cost"] >=0) & (x["Revenue"]>=0),"Revenue"].count()
#true

np.int64(55555)

In [ ]:
x["Engagement_Score"].describe() #from 35
x["Date"].describe()

count                            55555
mean     2024-12-21 00:56:22.593826048
min                2024-07-01 00:00:00
25%                2024-09-26 00:00:00
50%                2024-12-21 00:00:00
75%                2025-03-17 00:00:00
max                2025-06-24 00:00:00
Name: Date, dtype: object

In [ ]:
x[["Ci", "Lc", "Cl", "Cc","ROI_check"]] = x[["Ci", "Lc", "Cl", "Cc","ROI_check"]].round(2)

In [ ]:
x.to_csv("campaigns.csv", index=False)
from google.colab import files
files.download("campaigns.csv")